title: Gira Patel
email: gira.patel94@gmail.com
description: I'm a visual designer that's passionate about digital, branding, and the entertainment industry. Other interests include tech, playlist-making, and motion graphics.
url: http://girapatel.co/

baseurl: ""
url: http://girapatel.co/
permalink: /:title/

exclude:
  - README.md
  - .sass-cache
  - Gemfile
  - Gemfile.lock
    
# Build settings
#markdown: kramdown
#theme: minima
#plugins:
 # - jekyll-feed
